openapi: 3.0.0
info:
  title: Disaster in Thailand API
  description: |
    This API provides information about common natural disaster happening in Thailand. 
    It's sperated into 4 categories:
    * Overall monthly natural disaster in each region of Thailand. Raw data provided by Thai Meteorogical DepartMent (TMD).
    * Earthquake data in Thailand between 2011 and 2021. Raw data provided by Eathquake Observation Division.
    * Landslide risks area in Thailand. Raw data provided by Departmet of Mineral Resources (DMR).
    * Rainfall and storm data gathered by our group in Google form.
  version: 3.0.0
servers:
  - url: /disaster-api
paths:
  /disaster:
    get:
      summary: Returns a list of natural disaster happening in Thailand
      tags:
        - disaster
      operationId: controller.get_disaster
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DisasterBasic'
  /disaster/{month}:
    parameters:
    - name: month
      in: path
      required: true
      description: month name in Thai
      schema:
        type: string
    get:
      summary: Returns complete details of the specified month disaster
      tags: 
        - disaster
      operationId: controller.get_disaster_details
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DisasterDetail'
      
              
  /earthquake:
    get:
      summary: Returns a list of earthquake happening in Thailand.
      tags: 
        - earthquake
      operationId: controller.get_earthquake
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EarthquakeBasic'
  /earthquake/{province}:
    parameters:
    - name: province
      in: path
      required: true
      description: Province name in Thai
      schema:
        type : string
    get:
      summary: Returns complete details of the specified province earthquake 
      tags: 
        - earthquake
      operationId: controller.get_earthquake_details
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EarthquakeDetail'
  /earthquake/{province}/average:
    parameters:
    - name: province
      in: path
      required: true
      description: Province name in Thai
      schema:
        type : string
    get:
      summary: Returns average magnitude and phrase of earthquake for the specified province 
      tags: 
        - earthquake
      operationId: controller.get_average_magnitude_and_phrase
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EarthquakeAverage'
  /landslide:
    get:
      summary: Returns a list of landslide risk area in Thailand.
      tags: 
        - landslide
      operationId: controller.get_landslide
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LandslideBasic'
  /landslide/ratio:
    get:
      summary: Returns a value of landslide risk village and earthquake in Thailand.
      tags: 
        - landslide
      operationId: controller.get_landslide_and_earthquake_ratio
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LandEarthQuakeRatio'

components:
  schemas:
    DisasterBasic:
      type: object
      properties:
        month:
          type: string
        north:
          type: string
        north-east:
          type: string
        central:
          type: string
        east: 
          type: string
        south-east:
          type: string
        south-west:
          type: string
    DisasterDetail:
      type: object
      properties:
        month:
          type: string
        north:
          type: string
        north-east:
          type: string
        central:
          type: string
        east: 
          type: string
        south-east:
          type: string
        south-west:
          type: string
    EarthquakeBasic:
      type: object
      properties:
        center:
          type: string
        magnitude:
          type: number
    EarthquakeDetail:
      type: object
      properties:
        center:
          type: string
        magnitude:
          type: number
        date:
          type: string
        lat:
          type: number
        lon:
          type: number
        depth:
          type: integer
        phrase:
          type: integer
    EarthquakeAverage:
      type: object
      properties:
        magnitude:
          type: number
        phrase:
          type: number
    LandslideBasic:
      type: object
      properties:
        province:
          type: string
        risk-landslide-area:
          type: integer
    LandEarthQuakeRatio:
      type: object
      properties:
        province:
          type: string
        number_of_earthquake:
          type: integer
        risk-landslide-village:
          type: integer
    
