openapi: 3.0.0
info:
  title: Disaster in Thailand API
  description: |
    This API provides information about common natural disaster happening in Thailand. 
    It's sperated into 4 categories:
    * Overall monthly natural disaster in each region of Thailand. Raw data provided by Thai Meteorogical DepartMent (TMD).
    * Earthquake data in Thailand between 2011 and 2021. Raw data provided by Eathquake Observation Division.
    * Landslide risks area in Thailand. Raw data provided by Departmet of Mineral Resources (DMR).
    * Rainfall and storm data gathered by our group in Google form.
  version: 3.0.0
servers:
  - url: /disaster-api
paths:
  /disaster:
    get:
      summary: Returns a list of natural disaster happening in Thailand
      tags:
        - disaster
      operationId: controller.get_disaster
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DisasterBasic'
  /disaster/{month}:
    parameters:
    - name: month
      in: path
      required: true
      description: month name in Thai
      schema:
        type: string
    get:
      summary: Returns complete details of the specified month disaster
      tags: 
        - disaster
      operationId: controller.get_disaster_details
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DisasterBasic'
      
              
  /earthquake:
    get:
      summary: Returns a list of earthquake happening in Thailand.
      tags: 
        - earthquake
      operationId: controller.get_earthquake
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EarthquakeBasic'
  /earthquake/{province}:
    parameters:
    - name: province
      in: path
      required: true
      description: Province name in Thai
      schema:
        type : string
    get:
      summary: Returns complete details of the specified province earthquake 
      tags: 
        - earthquake
      operationId: controller.get_earthquake_details
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EarthquakeDetail'
  /earthquake/{province}/average:
    parameters:
    - name: province
      in: path
      required: true
      description: Province name in Thai
      schema:
        type : string
    get:
      summary: Returns average magnitude and phrase of earthquake for the specified province 
      tags: 
        - earthquake
      operationId: controller.get_average_magnitude_and_phrase
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EarthquakeAverage'
  /earthquake/{province}/numOfEarthquakes:
    parameters:
    - name: province
      in: path
      required: true
      description: Province name in Thai
      schema:
        type : string
    get:
      summary: Returns the number of earthquake occuring on the specified province 
      tags: 
        - earthquake
      operationId: controller.get_province_numbers_of_earthquakes
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EarthquakeNumber'


  /landslide:
    get:
      summary: Returns a list of landslide risk area in Thailand.
      tags: 
        - landslide
      operationId: controller.get_landslide
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/LandslideBasic'
  /landslide/{province}:
    parameters:
      - name: province
        in: path
        required: true
        description: Province name in Thai
        schema:
          type: string
    get:
      summary: Returns complete details of the specified province landslide.
      tags:
        - landslide
      operationId: controller.get_landslide_details
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LandslideDetail'
  /landslide/ratio:
    get:
      summary: Returns a value of landslide risk village and earthquake in Thailand.
      tags: 
        - landslide
      operationId: controller.get_landslide_earthquake_ratio
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LandslideEarthquakeRatio'
  /landslide/{province}/ratio:
    parameters:
    - name: province
      in: path
      required: true
      description: Province name in Thai
      schema:
        type : string
    get:
      summary: Returns a value of landslide risk village and earthquake of specified province.
      tags: 
        - landslide
      operationId: controller.get_province_landslide_earthquake_ratio
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LandslideEarthquakeRatio'


  /survey:
    get:
      summary: Returns a list of survey risk disaster area in Thailand.
      tags:
        - survey
      operationId: controller.get_survey
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Surveys'


  /survey/{province}:
    parameters:
      - name: province
        in: path
        required: true
        description: Province name in Thai
        schema:
          type: string
    get:
      summary: Returns complete details of the specified province survey.
      tags:
        - survey
      operationId: controller.get_survey_details
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Surveys'
          links:
            avgMonthlyRainfalls:
              operationId: controller.get_average_survey_rain
              parameters:
                province: $response.body#/province

  /survey/{province}/average:
    parameters:
      - name: province
        in: path
        required: true
        description: Province name in Thai
        schema:
          type: string
    get:
      summary: Returns average rain duration and rain amount for the specified province
      tags:
        - survey
      operationId: controller.get_average_survey_rain
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SurveyRainAverage'

components:
  schemas:
    DisasterBasic:
      type: object
      properties:
        month:
          type: string
        section:
          type: string
        disaster:
          type: string
    EarthquakeBasic:
      type: object
      properties:
        center:
          type: string
        magnitude:
          type: number
    EarthquakeDetail:
      type: object
      properties:
        center:
          type: string
        magnitude:
          type: number
        date:
          type: string
        lat:
          type: number
        lon:
          type: number
        depth:
          type: integer
        phrase:
          type: integer
    EarthquakeAverage:
      type: object
      properties:
        province: 
          type: string
        average_magnitude:
          type: number
        average_phrase:
          type: number
    EarthquakeNumber:
      type: object
      properties:
        number_of_earthquake: 
          type: integer
    LandslideBasic:
      type: object
      properties:
        province:
          type: string
        risk-landslide-area:
          type: integer
    LandslideDetail:
      type: object
      properties:
        province:
          type: string
        district:
          type: integer
        sub-district:
          type: integer
        risk-landslide-village:
          type: integer
        risk-landslide-area:
          type: integer
    LandslideEarthquakeRatio:
      type: object
      properties:
        province:
          type: string
        number_of_earthquake:
          type: integer
        risk-landslide-village:
          type: integer
    Surveys:
      type: object
      properties:
        province:
          type: string
        section:
          type: string
        encounted_disaster:
          type: string
        common_disaster:
          type: string
        dangerous_disaster:
          type: string
        rain_duration:
          type: integer
        rain_heaviness:
          type: string
        rain_amount:
          type: integer
    SurveyRainAverage:
      type: object
      properties:
        province:
          type: string
        average_rain_duration:
          type: number
        average_rain_amount:
          type: number
